### ISSUE TITLE
Setup travis

### ISSUE THREAD

**Issue by ahartikainen** [stan-dev/pystan-next#5]
Travis needs `.travis.yml`-file.

    Could not find .travis.yml, using standard configuration

**Comment by mkcor** [comment]
I guess commit 016643c3aca9dc22667acaa1bdf509d64a52569c by @ariddell has taken care of this issue.

**Comment by mkcor** [comment]
Could we display build status with a badge in the README? So that we can see it failed:
![build_badge](https://user-images.githubusercontent.com/2227806/35179718-c7bf0592-fd6d-11e7-9d0c-8d26bcef2543.png)
I don't know how to add badges in ReStructuredText... I can convert the README into Markdown if you allow me to.
