### ISSUE TITLE
use keyword-only API

### ISSUE THREAD

**Issue by ariddell** [stan-dev/pystan-next#7]
There's a new trick in Python 3 which is tailor-made for calls to the sampling functions and any functions which have lots of arguments. It is possible to require that arguments be passed by keyword.

Details: https://www.python.org/dev/peps/pep-3102/

I believe one uses it like this:

```
def hmc_nuts(*, iter, warmup, adapt, kwarg1, kwarg2, kwarg3, kwarg4):
```

**Comment by ahartikainen** [comment]
Yes, it's a good way to force user be explicit.

It's also possible to allow some args if needed

    def hmc_nuts(iter, warmup, *, adapt, kwarg1, kwarg2, kwarg3, kwarg4):

**Comment by riddell-stan** [comment]
I'm closing this because it's a little tricky to implement in practice without having an exhaustive list of possible arguments. `httpstan` might have this, but I suspect pystan will not. Likely easier to raise an error (in `httpstan`) when the user provides an extra argument.

**Comment by riddell-stan** [comment]
Reopening because (1) I'd like to make sure it gets implemented in httpstan and (2) I think there's a way to do this on the pystan side. Maybe something like ``myfunction(*ignore, **kwargs)``. I could be wrong.

Here's a link to the relevant PEP: [PEP 3102 -- Keyword-Only Arguments](https://www.python.org/dev/peps/pep-3102/).

This is an important one. There are many Stan functions which should be keyword-only. It would be, for example, imprudent to ever try to set `adapt_delta` with a position argument.

**Comment by riddell-stan** [comment]
Not an issue right now since we don't support anything other than `Model.sample`, which already does not use positional arguments.
